from langchain_core.prompts import ChatPromptTemplate
from vectorization import retriever
from app import model
from github import Github

g = Github()

template = """
    You are a code-review assistant that is responsible for helping users improve the quality of their code. You will be given a diff file generated by github when a user makes a change. Based on that change, you should suggest improvements that can be made to the code (performance, syntax, structure, etc). Provide these metrics in a well-structured format. 

    Here is some relevant files based off the diff: {files}
"""

prompt = ChatPromptTemplate.from_template(template)
chain = prompt | model

repo = g.get_repo(f"SahusBhandary-Student/test_repo")
contents = repo.get_contents('')
commit = repo.get_commit("3d5c0db9f7ed9dd17007b9c59a199a7c918b232e")

target_filename = "test_chunker.py"
diff = ""

for file in commit.files:
    if file.filename == target_filename:
        diff = file.patch
        break


files = retriever.invoke(diff)
result = chain.invoke({"files": files})
print(result)


# Ollama Test
# import requests

# url = "http://localhost:11434/api/chat"

# data = {
#     "model": "qwen2.5-coder:7b",
#     "stream": False,
#     "messages": [
#         {"role": "system", "content": "You are a code review assistant."},
#         {"role": "user", "content": "Write me the code for the fibonacci sequence."},
#     ],
# }

# response = requests.post(url, json=data)
# response.raise_for_status()

# print(response.json()["message"]["content"])