from langchain_core.prompts import ChatPromptTemplate
from vector import vectorize_repo
from app import model
from github import Github
from parser import FileParser
import os

g = Github()

def get_llm_response(repo, commit_hash):

    template = """
        You are a code-review assistant that is responsible for helping users improve the quality of their code. You will be given a diff file generated by github when a user makes a change. Based on that change, you should suggest improvements that can be made to the code (performance, syntax, structure, etc).

        Here is some relevant files based off the diff: {files}
    """

    prompt = ChatPromptTemplate.from_template(template)
    chain = prompt | model
    parser = FileParser()

    commit = repo.get_commit(commit_hash)

    diff = ""

    for file in commit.files:
        if file.patch:
            diff += f"\n--- {file.filename}\n{file.patch}\n"
            break
    
    retriever = vectorize_repo(repo)
    files = retriever.invoke(diff)

    result = chain.invoke({"files": files})
    return result


# repo = g.get_repo('SahusBhandary-Student/test_repo')
# get_llm_response(repo, None)

# Ollama Test
# import requests

# url = "http://localhost:11434/api/chat"

# data = {
#     "model": "qwen2.5-coder:7b",
#     "stream": False,
#     "messages": [
#         {"role": "system", "content": "You are a code review assistant."},
#         {"role": "user", "content": "Write me the code for the fibonacci sequence."},
#     ],
# }

# response = requests.post(url, json=data)
# response.raise_for_status()

# print(response.json()["message"]["content"])